config/routes.rb
VendorTool::Application.routes.draw do

  root :to => 'projects#index'

  match "/project/:project_id/item/new" => 'items#new'
  match "/project/:project_id/item/:item_id/edit" => 'items#edit'
  delete "/project/:project_id/item/:item_id" => 'items#destroy'
  
  match "/project/:project_id/item/new/confirm" => 'items#confirm'

  resources :projects
  resources :employees
  resources :items
  resource :session, :only => [:new, :create, :destroy]

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :code, :description, :employee_id, :name

  validates_presence_of :name, :employee_id

  belongs_to :employee
  has_many :items
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :require_project_owner_or_admin, :only => [:edit, :destroy] 
  before_filter :require_logged_in, :only => :show

  def require_logged_in
    if current_user.nil?
      redirect_to root_url, notice: "You must logged in first."
    end
  end

  def require_project_owner_or_admin
    employee = Employee.find_by_id(session[:user_id])
    project = Project.find_by_id(params[:id])
    project_owner_id = project.employee_id
    if employee.system_admin == FALSE && (employee.nil? || employee.id != project_owner_id)
      redirect_to projects_url, notice: "Only Project Owner can edit and delete projects."
    end
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <% if current_user.system_admin %>
    <div class="field">
      <%= f.label :employee_id %><br />
      <%= f.collection_select :employee_id, Employee.all, :id, :email %>
    </div>
  <% else %>  
      <%= f.hidden_field :employee_id, :value => current_user.id %>
  <% end %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% if current_user %>
  <h1>Current projects</h1>

  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Description</th>
      <th>Project owner</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.code %></td>
        <td><%= project.description %></td>
        <% if project.employee != nil %>
          <td><%= project.employee.first_name %><%= project.employee.last_name %></td>
          <td><%= link_to 'Show', project %></td>
        <% end %>
        <!-- Edit, Delete, and Add Item is only available to Project Owner -->
        <% if current_user.system_admin || (current_user.id == project.employee_id) %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Add Item', "/project/#{project.id}/item/new" %></td>
        <% end %>
      </tr>
    <% end %>

  </table>

  <br />

  <%= link_to 'New Project', new_project_path %>

<% else %>

  <h2>Please login</h2>
  <%= form_tag session_url do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag 'Sign In' %>
    </div>
  <% end %>

<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="container">
<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Code:</b>
  <%= @project.code %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Project owner:</b>
  <%= full_name = "#{@project.employee.first_name} #{@project.employee.last_name}" %>
</p>
</div>

<table class="table table-striped">
  <tr>
    <td class="span2 left-side-header">Vendor</td>	
    <% @project.items.each do |item| %>
      <th><%= item.vendor %></th>
    <% end %>
  </tr>

  <tr>
    <td class="left-side-header">Vendor email</td>	
    <% @project.items.each do |item| %>
      <td><%= item.vendor_email %></td>
    <% end %>
  </tr>
  
  <tr>
    <td class="left-side-header">Thumbnail</td>  
    <% @project.items.each do |item| %>
      <td>
        <% if item.photo_file_name.present? %>
          <%= image_tag item.photo.url(:thumb) %>
        <% end %>
      </td>
    <% end %>  
  </tr>

  <tr>
    <td class="left-side-header">Item #</td>	
    <% @project.items.each do |item| %>
      <td><%= item.item_no %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Source from</td>	
    <% @project.items.each do |item| %>
    <td><%= item.source_from %></td>
  <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Vendor brand</td>	
    <% @project.items.each do |item| %>
      <td><%= item.vendor_brand %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Model #</td>	
    <% @project.items.each do |item| %>
      <td><%= item.model_no %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Descrption</td>
    <% @project.items.each do |item| %>
      <td><%= item.description %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">FOB (US$)</td>
    <% @project.items.each do |item| %>
      <td><%= item.fob %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Payment terms</td>
    <% @project.items.each do |item| %>
      <td><%= item.payment_terms %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">MOQ (pieces)</td>
    <% @project.items.each do |item| %>
      <td><%= item.moq %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Repeat Order Lead-time (days)</td>
    <% @project.items.each do |item| %>
      <td><%= item.repeat_order_leadtime %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Packaging</td>
    <% @project.items.each do |item| %>
      <td><%= item.packaging %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Suggested Retail (US$)</td>
    <% @project.items.each do |item| %>
      <td><%= item.suggested_retail %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Tooling complete (Y/N)</td>
    <% @project.items.each do |item| %>
      <td><%= item.tooling_complete %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Remarks</td>
    <% @project.items.each do |item| %>
      <td><%= item.remarks %></td>
    <% end %>
  </tr>

  <tr>
  	<td class="left-side-header">Edit</td>
    <% @project.items.each do |item| %>
      <td><%= link_to 'Edit', "/project/#{@project.id}/item/#{item.id}/edit" %></td>
    <% end %>
  </tr>
  <tr>
  	<td class="left-side-header">Delete item</td>
    <% @project.items.each do |item| %>
      <td><%= link_to 'Delete', "/project/#{@project.id}/item/#{item.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
 
</table>

 

<%= link_to 'Edit Project', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> | 

<% if current_user.system_admin || (current_user.id == @project.employee_id) %>
  <%= link_to 'Add Item', "/project/#{@project.id}/item/new" %></td>
<% end %>