config/routes.rb
VendorTool::Application.routes.draw do

  root :to => 'projects#index'

  match "/project/:project_id/item/new" => 'items#new'
  match "/project/:project_id/item/:item_id/edit" => 'items#edit'
  delete "/project/:project_id/item/:item_id" => 'items#destroy'
  
  match "/project/:project_id/item/new/confirm" => 'items#confirm'

  resources :projects
  resources :employees
  resources :items
  resource :session, :only => [:new, :create, :destroy]

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :fob, :fob_port, :item_no, :model_no, :moq, :packaging, :payment_terms, :project_id, :remarks, :repeat_order_leadtime, :source_from, :suggested_retail, :tooling_complete, :vendor, :vendor_brand, :vendor_email
  attr_accessible :photo
  attr_accessible :photo_file_name, :photo_content_type, :photo_file_size
 
  belongs_to :project

  validates_presence_of :vendor, :vendor_email

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :url  => "/assets/items/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/items/:id/:style/:basename.:extension"

  # has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" },
  #                   :url  => ":s3_sg_url",
  #                   :path => ":rails_root/public/assets/items/:id/:style/:basename.:extension"

  validates_attachment :photo, #:presence => true,
                       :content_type => { :content_type => ['image/jpeg', 'image/png'] },
                       :size => { :less_than => 1.megabytes }

# Notes from Paperclip 3.0
#=========================
# Paperclip 3.0 introduces a non-backward compatible change in your attachment
# path. This will help to prevent attachment name clashes when you have
# multiple attachments with the same name. If you didn't alter your
# attachment's path and are using Paperclip's default, you'll have to add
# `:path` and `:url` to your `has_attached_file` definition. For example:

#     has_attached_file :avatar,
#       :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
#       :url => "/system/:attachment/:id/:style/:filename"

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :require_project_owner_or_admin, :only => [:edit, :destroy] 
   
  def require_project_owner_or_admin
    employee = Employee.find_by_id(session[:user_id])
    project = Project.find_by_id(params[:project_id])
    project_owner_id = project.employee_id
    if employee.system_admin == FALSE && (employee.nil? || employee.id != project_owner_id)
      redirect_to project_url(project.id), notice: "Only Project Owner can edit and delete project items"
    end
  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @project = Project.find_by_id(params[:project_id])
    @item = Item.new

    respond_to do |format|
      if @project.nil?
        redirect_to root_url, notice: 'Project not found.'
        return
      else
        format.html # new.html.erb
      end
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:item_id])
    @project = Project.find_by_id(params[:project_id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])
    @project = Project.find_by_id(@item.project.id)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @project, notice: 'Item was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    @project = Project.find_by_id(@item.project_id)

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @project, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:item_id])
    @project = Project.find_by_id(@item.project_id)

    @item.destroy

    respond_to do |format|
      format.html { redirect_to @project, notice: 'Item was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @item = Item.new(params[:item])
    unless @item.valid?
      render :action => :new
    else       
  end
end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%#= form_for(@item) do |f| %>
<%= form_for @item, :html => { :multipart => true } do |f| %>
<%#= form_for @item, :url => {:action => "confirm"} do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>* indicate required fields</p><br>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.hidden_field :project_id, :value => @project.id %>
    <%= f.text_field :project, :value => @project.name, :disabled => true %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :vendor, 'Vendor name*' %>
    <%= f.text_field :vendor %>
  </div>
  <div class="field">
    <%= f.label :vendor_email, 'Vendor email*' %>
    <%= f.text_field :vendor_email %>
  </div>

  <div class="field">
    <%= f.label :item_no %>
    <%= f.text_field :item_no %>
  </div>
  <div class="field">
    <%= f.label :source_from %>
    <%= f.text_field :source_from %>
  </div>
  <div class="field">
    <%= f.label :vendor_brand %>
    <%= f.text_field :vendor_brand %>
  </div>
  <div class="field">
    <%= f.label :model_no %>
    <%= f.text_field :model_no %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :fob, 'FOB' %>
    <%= f.text_field :fob %>
  </div>
  <div class="field">
    <%= f.label :fob_port, 'FOB port' %>
    <%= f.text_field :fob_port %>
  </div>
  <div class="field">
    <%= f.label :payment_terms %>
    <%= f.text_field :payment_terms %>
  </div>
  <div class="field">
    <%= f.label :moq, 'MOQ'%>
    <%= f.number_field :moq %>
  </div>
  <div class="field">
    <%= f.label :repeat_order_leadtime %>
    <%= f.number_field :repeat_order_leadtime %>days
  </div>
  <div class="field">
    <%= f.label :packaging %>
    <%= f.text_field :packaging %>
  </div>
  <div class="field">
    <%= f.label :suggested_retail %>
    <%= f.text_field :suggested_retail %>
  </div>
  <div class="field">
    <%= f.label :tooling_complete %>
    <%= f.check_box :tooling_complete %>
  </div>
  <div class="field">
    <%= f.label :remarks %>
    <%= f.text_area :remarks %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%#= link_to 'Show', @item %> 
<%= link_to 'Show', "/project/#{@item.project_id}/item/#{@item.id}" %> |
<%= link_to 'Back', :back %>

app/views/items/index.html.erb
<h1>Listing items</h1>


<% @items.each do |item| %>
  <ol>
    <li>Project:<%= item.project.name %></li>
    
    <li>Item no.:<%= item.item_no %></li>
    <li>Source From:<%= item.source_from %></li>
    <li>Vendor / Brand:<%= item.vendor_brand %></li>
    <li>Model No.:<%= item.model_no %></li>
    <li>Description:<%= item.description %></li>
    <li>FOB:<%= item.fob %></li>
    <li>FOB Port:<%= item.fob_port %></li>
    <li>Payment terms<%= item.payment_terms %></li>
    <li>Item MOQ:<%= item.moq %></li>
    <li>Repeat order leadtime:<%= item.repeat_order_leadtime %>days</li>
    <li>Packaging:<%= item.packaging %></li>
    <li>Suggested retail:<%= item.suggested_retail %></li>
    <li>Tooling complate:<%= item.tooling_complete %></li>
    <li>Remarks:<%= item.remarks %></li>
    <li>Project ID:<%= item.project_id %></li>
    <li>Vendor:<%= item.vendor %></li>
    <li>Vendor email:<%= item.vendor_email %></li>
    <br>
    <li><%= link_to 'Show', item %></li>
    <%#= link_to 'Edit', edit_item_path(item) %>
    <%#= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
  </ol>
<% end %>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @item.project.name %>
</p>

<%= image_tag @item.photo.url(:medium) %>

<p>
  <b>Item no:</b>
  <%= @item.item_no %>
</p>

<p>
  <b>Source from:</b>
  <%= @item.source_from %>
</p>

<p>
  <b>Vendor brand:</b>
  <%= @item.vendor_brand %>
</p>

<p>
  <b>Model no:</b>
  <%= @item.model_no %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Fob:</b>
  <%= @item.fob %>
</p>

<p>
  <b>Fob port:</b>
  <%= @item.fob_port %>
</p>

<p>
  <b>Payment terms:</b>
  <%= @item.payment_terms %>
</p>

<p>
  <b>Moq:</b>
  <%= @item.moq %>
</p>

<p>
  <b>Repeat order leadtime:</b>
  <%= @item.repeat_order_leadtime %>
</p>

<p>
  <b>Packaging:</b>
  <%= @item.packaging %>
</p>

<p>
  <b>Suggested retail:</b>
  <%= @item.suggested_retail %>
</p>

<p>
  <b>Tooling complete:</b>
  <%= @item.tooling_complete %>
</p>

<p>
  <b>Remarks:</b>
  <%= @item.remarks %>
</p>

<p>
  <b>Vendor:</b>
  <%= @item.vendor %>
</p>

<p>
  <b>Vendor email:</b>
  <%= @item.vendor_email %>
</p>


<%#= link_to 'Edit', edit_item_path(@item) %>
<%= link_to 'Edit', "/project/#{@item.project_id}/item/#{@item.id}/edit" %> |
<%= link_to 'Back', :back %>