config/routes.rb
VendorTool::Application.routes.draw do

  root :to => 'projects#index'

  match "/project/:project_id/item/new" => 'items#new'
  match "/project/:project_id/item/:item_id/edit" => 'items#edit'
  delete "/project/:project_id/item/:item_id" => 'items#destroy'
  
  match "/project/:project_id/item/new/confirm" => 'items#confirm'

  resources :projects
  resources :employees
  resources :items
  resource :session, :only => [:new, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VendorTool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

  <!-- Twitter Bootstrap  -->
  <script src="http://code.jquery.com/jquery-latest.js"></script>


</head>
<body>
  <div class="navbar">
  	<div class="navbar-inner">
  	  <div class="container">	
        <h2 class="brand">SheenwayTek Vendor Tool</h2>
        <ul class="nav actions">
          <li class="nav"><%= link_to 'Home', root_url%></li>
          <li class="nav"><%= link_to 'About Us', '#' %></li>
          <% if current_user != nil %>
            <% if current_user.system_admin %>
               <li class="nav"><%= link_to 'Employee list', employees_url %></li>
            <% end %>
          <% end %>
        </ul>
      </div> <!-- container -->
        <% if current_user %>
          <p>Welcome <%= current_user.email %>
          <%= link_to 'Sign Out', session_url, :method => 'delete' %></p>
        <% end %> 
    </div>  
  </div>

  <div class="container">
    <p id="notice"><%= notice %></p> 

    <%= yield %>
  </div>
</body>
</html>